name: Install Coda in R

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:

  install_coda:
    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-22.04, ubuntu-22.04-arm #,
            # I can't figure out windows or macos yet
            # windows-2025 , windows-11-arm ,
            # macos-13, macos-15
            ]
        R-version: ['4.4.0', 'latest'] # ['4.4.0', 'latest', '4.5.0']
        cran: 
          - {label: cloud, url: https://cloud.r-project.org/}
          - {label: p3m-linux-latest, url: https://p3m.dev/cran/__linux__/jammy/latest}
          - {label: p3m-linux-source, url: https://p3m.dev/cran/latest}
          - {label: p3m-linux-old, url: https://p3m.dev/cran/__linux__/jammy/2024-03-31}
        use_pak: [yes, no]

    runs-on: ${{ matrix.os }}
    container: rocker/r-ver:${{ matrix.R-version }}
    env:
        _USE_PAK: ${{ matrix.use_pak }}
        _IMAGE: rocker/r-ver:${{ matrix.R-version }}
        _CRAN: ${{ matrix.cran.url }}
        _R_PKG: data.table
        _VERBOSE: yes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install docker on Mac
        if: ${{ startsWith( matrix.os, 'macos' ) }}
        uses: docker/setup-docker-action@v4.3.0

      - name: Installing coda
        shell: bash
        run: |
          Rscript -e 'source("install.R")'

      - name: Save the output
        uses: actions/upload-artifact@v4.6.2
        with:
          path: |
              *yaml
          name: coda-install-${{ matrix.R-version }}-${{ matrix.os }}-${{ matrix.cran.label }}-${{ matrix.use_pak }}
    
  combine:
    runs-on: ubuntu-latest
    container: rocker/r-ver:latest
    needs: install_coda
    if: success() || failure()
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v5.0.0
        with:
            merge-multiple: true
            path: .

      - name: Dependencies
        run: |
          install2.r --error yaml

      - name: Combine all YAML files
        shell: Rscript {0}
        run: |
          
          library(yaml)
          
          files <- list.files(pattern = "*.yaml")
          out <- do.call(rbind, lapply(files, function(f) {
            y <- yaml.load_file(f)
            as.data.frame(t(unlist(y)), stringsAsFactors = FALSE)
          }))

          fn <- format(Sys.time(), "%Y-%m-%d_%H-%M-%S")
          fn <- paste0(fn, ".csv")

          write.csv(out, file = fn, row.names = FALSE)
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: install-file
          path: |
            *.csv

  commit:
    runs-on: ubuntu-latest
    needs: combine
    if: success() || failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          name: install-file

      - name: Commit changes
        run: |
          mv *.csv data/
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data/*.csv || echo "Nothing to add"
          git commit -m "Add coda installation summary" || echo "Nothing to commit"
          git push || echo "Nothing to push"
